language: python
branches:
  only:
    - source
install:
  - pip install --allow-external PIL --allow-unverified PIL pelican ghp-import Markdown beautifulsoup4 pypandoc PIL
script:
  - make publish github
env:
  global:
    secure: SQhpImRQiS2bYQw+ZhwI18PWMP4d6ssvII8xoP+XMN6M2OrBtEwFc4QDyw714tjDzdjur4iDWa9LQmz/Yh+43Jj5SN6FwDhTlUMbaTV/HUAWru2tY6o2mZ0jkGewhOgyvJoX/EKJ4J2HrVtTxdJpcXb7mjjnhlV7u4yh+PlK5ss=

